SET IDENTITY_INSERT [dbo].[Director] ON
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (1, N'James Cameron')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (2, N'Alejandro González Iñarritu')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (3, N'Darren Aronofsky')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (4, N'Ted Demme')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (5, N'Mike Nichols')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (6, N'Oliver Hirschbiegel')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (7, N'Denis Villeneuve')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (8, N'Danis Tanovic')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (9, N'Andy Wachowski')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (10, N'Lana Wachowski')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (11, N'Rob Marshall')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (12, N'Alejandro Amenábar')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (13, N'Guy Ritchie')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (14, N'Joel Schumacher')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (15, N'Barry Sonnenfeld')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (16, N'Sam Raimi')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (19, N'David Fincher')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (32, N'Chris Columbus')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (33, N'John Carpenter')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (34, N'Martin Scorsese')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (37, N'Bigas Luna')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (38, N'Lee Tamahori')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (39, N'Chi Leung ''Jacob'' Cheung')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (40, N'Hark Tsui')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (41, N'Siu-Tung Ching')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (42, N'Walter Hill')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (43, N'Chuck Russell')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (44, N'Ronny Yu')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (45, N'Christopher Nolan')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (46, N'John Lamb')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (48, N'Tim Burton')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (49, N'Chuck Jones')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (50, N'Roman Polanski')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (51, N'Federico Fellini')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (52, N'Curtis Hanson')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (53, N'Anne Fletcher')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (54, N'Ridley Scott')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (55, N'John Jopson')
INSERT INTO [dbo].[Director] ([DirectorId], [Name]) VALUES (56, N'Ron Howard')
SET IDENTITY_INSERT [dbo].[Director] OFF
