SET IDENTITY_INSERT [dbo].[Actor] ON
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (1, N'Sigourney Weaver')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (2, N'Michael Bihen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (3, N'Carrie Henn')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (4, N'Emilio Echevarría')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (5, N'Gael García Bernal')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (6, N'Goya Toledo')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (7, N'Natalie Portman')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (8, N'Mila Kunis')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (9, N'Vincent Cassel')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (10, N'Johnny Deep')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (11, N'Penélope Cruz')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (12, N'Franka Potente')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (13, N'Jude Law')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (14, N'Clive Owen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (15, N'Julia Roberts')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (16, N'Moritz Bleibtreu')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (17, N'Christian Berkel')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (18, N'Oliver Stokowski')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (19, N'Lubna Azabal')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (20, N'Mélissa Désormeaux-Poulin')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (21, N'Maxim Gaudette')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (22, N'Branko Djuric')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (23, N'Rene Bitorajac')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (24, N'Filip Sovagovic')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (25, N'Val Kilmer')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (26, N'Tommy Lee Jones')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (27, N'Jim Carrey')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (28, N'Nicole Kidman')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (29, N'Mustafa Kamel')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (30, N'Hussein Sami')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (31, N'Rémy Girard')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (32, N'Will Smith')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (33, N'Linda Fiorentino')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (34, N'Vincent D''Onofrio')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (35, N'James Franco')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (36, N'Rachel Weisz')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (37, N'Michelle Williams')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (46, N'Jesse Eisenberg')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (47, N'Rooney Mara')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (48, N'Bryan Barter')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (49, N'Dustin Fitzsimons')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (57, N'Macaulay Culkin')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (58, N'Joe Pesci')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (59, N'Daniel Stern')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (60, N'Catherine O''Hara')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (61, N'Kurt Russell')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (62, N'Lee Van Cleef')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (63, N'Ernest Borgnine')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (64, N'Donald Pleasence')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (65, N'Leonardo DiCaprio')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (66, N'Daniel Day-Lewis')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (67, N'Cameron Diaz')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (68, N'Jim Broadbent')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (77, N'Biel Duran')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (78, N'Mathilda May')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (79, N'Gérard Darmon')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (80, N'Miguel Poveda')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (81, N'Rena Owen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (82, N'Temuera Morrison')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (83, N'Mamaengaroa Kerr-Bell')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (84, N'Julian Arahanga')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (85, N'Andy Lau')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (86, N'Sung-kee Ahn')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (87, N'Zhiwen Wang')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (88, N'Bingbing Fan')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (89, N'Ekin Cheng')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (90, N'Cecilia Cheung')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (91, N'Louis Koo')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (92, N'Patrick Tam')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (93, N'Kelly Chen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (94, N'Donnie Yen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (95, N'Leon Lai')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (96, N'Xiaodong Guo')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (97, N'Michael Beck')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (98, N'James Remar')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (99, N'Dorsey Wright')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (100, N'Brian Tyler')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (101, N'Heather Langenkamp')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (102, N'Craig Wasson')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (103, N'Patricia Arquette')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (104, N'Robert Englund')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (105, N'Angus Macfadyen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (106, N'Mario Yedidia')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (107, N'Marley Shelton')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (108, N'Chao Li Chi')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (109, N'Guy Pearce')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (110, N'Carrie-Anne Moss')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (111, N'Joe Pantoliano')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (112, N'Mark Boone Junior')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (113, N'George Rowe')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (114, N'Diane Webber')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (115, N'Gaby Martone')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (116, N'Timothy Carey')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (121, N'Johnny Depp')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (122, N'Michelle Pfeiffer')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (123, N'Helena Bonham Carter')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (124, N'Eva Green')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (125, N'N/A')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (126, N'Ewan McGregor')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (127, N'Jon Bernthal')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (128, N'Tim Preece')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (129, N'James Belushi')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (130, N'Peter Gonzales Falcon')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (131, N'Fiona Florence')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (132, N'Britta Barnes')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (133, N'Pia De Doses')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (134, N'Eminem')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (135, N'Kim Basinger')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (136, N'Mekhi Phifer')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (137, N'Brittany Murphy')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (138, N'Sandra Bullock')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (139, N'Ryan Reynolds')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (140, N'Mary Steenburgen')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (141, N'Craig T. Nelson')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (142, N'Christian Bale')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (143, N'Joel Edgerton')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (144, N'John Turturro')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (145, N'Aaron Paul')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (146, N'Elton John')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (147, N'Tim Rice')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (148, N'Roy Edward Disney')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (149, N'Jeffrey Katzenberg')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (150, N'Russell Crowe')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (151, N'Ed Harris')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (152, N'Jennifer Connelly')
INSERT INTO [dbo].[Actor] ([ActorId], [Name]) VALUES (153, N'Christopher Plummer')
SET IDENTITY_INSERT [dbo].[Actor] OFF
