SET IDENTITY_INSERT [dbo].[Genre] ON
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (1, N'Action')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (2, N'Drama')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (3, N'Adventure')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (4, N'Animation')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (5, N'Comedies')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (6, N'Sci-Fi')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (7, N'Crime')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (8, N'Thrillers')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (9, N'Fantasy')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (10, N'Family')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (11, N'Mystery')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (12, N'Romance')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (13, N'Sport')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (14, N'Horror')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (15, N'War')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (16, N'Westerns')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (17, N'Reality-Tv')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (18, N'History')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (19, N'Documentaries')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (20, N'Game Shows')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (21, N'Music')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (22, N'Biographies')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (23, N'Musicals')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (24, N'News')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (25, N'Talk Shows')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (26, N'Film-Noir')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (27, N'Comedy')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (28, N'Biography')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (29, N'Thriller')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (30, N'Short')
INSERT INTO [dbo].[Genre] ([GenreId], [Name]) VALUES (31, N'Documentary')
SET IDENTITY_INSERT [dbo].[Genre] OFF
