SET IDENTITY_INSERT [dbo].[Country] ON
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (1, N'United States')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (2, N'United Kingdom')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (3, N'Canada')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (4, N'Germany')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (5, N'France')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (6, N'Italy')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (7, N'Japan')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (8, N'Mexico')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (9, N'Spain')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (10, N'Australia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (11, N'Philippines')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (12, N'India')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (13, N'Hong Kong')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (14, N'China')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (15, N'Ireland')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (16, N'West Germany')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (17, N'Argentina')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (18, N'South Africa')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (19, N'Russia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (20, N'Israel')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (21, N'Netherlands')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (22, N'Switzerland')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (23, N'Brazil')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (24, N'South Korea')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (25, N'Sweden')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (26, N'Austria')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (27, N'Belgium')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (28, N'Hungary')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (29, N'Poland')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (30, N'New Zealand')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (31, N'Denmark')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (32, N'Greece')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (33, N'Czech Republic')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (34, N'Romania')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (35, N'Yugoslavia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (36, N'Colombia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (37, N'Norway')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (38, N'Thailand')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (39, N'Chile')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (40, N'Luxembourg')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (41, N'Taiwan')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (42, N'Peru')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (43, N'Puerto Rico')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (44, N'Iran')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (45, N'Nigeria')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (46, N'Finland')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (47, N'Iceland')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (48, N'United Arab Emirates')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (49, N'Bulgaria')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (50, N'Morocco')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (51, N'Singapore')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (52, N'Turkey')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (53, N'Ukraine')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (54, N'Soviet Union')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (55, N'Indonesia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (56, N'Portugal')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (57, N'Dominican Republic')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (58, N'Egypt')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (59, N'Venezuela')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (60, N'Ecuador')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (61, N'Bahamas')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (62, N'Cuba')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (63, N'Panama')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (64, N'Uruguay')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (65, N'Vietnam')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (66, N'Croacia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (67, N'Ethiopia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (68, N'Jamaica')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (69, N'Cambodia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (70, N'Malaysia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (71, N'Armenia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (72, N'Aruba')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (73, N'Guatemala')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (74, N'Serbia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (75, N'Lebanon')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (76, N'Lithuania')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (77, N'Pakistan')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (78, N'Federal Republic of Yugoslavia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (79, N'Bosnia and Herzegovina')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (80, N'Bolivia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (81, N'Cameroon')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (82, N'Czechoslovakia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (83, N'Kenya')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (84, N'Liechtenstein')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (85, N'Republic of Macedonia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (86, N'Tanzania')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (87, N'Afghanistan')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (88, N'Albania')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (89, N'Haiti')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (90, N'Jordan')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (91, N'Sri Lanka')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (92, N'Latvia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (93, N'Mongolia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (94, N'Malta')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (95, N'Palestinian Territory')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (96, N'Bangladesh')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (97, N'Belarus')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (98, N'Belize')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (99, N'Costa Rica')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (100, N'Slovenia')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (101, N'USA')
INSERT INTO [dbo].[Country] ([CountryId], [Name]) VALUES (102, N'UK')
SET IDENTITY_INSERT [dbo].[Country] OFF
